// Copy strings — EN + JP + ES — literary tone
const COPY = {
  en: {
    nav: { home: 'Home', characters: 'Characters' },
    hero: {
      eyebrow: 'A VR & Desktop Experience · Steam · Q4 2027',
      tagline: 'A dream before the last one.',
      meta_left: 'CH.00 · The Caretaker',
      meta_right: 'Scroll to enter',
    },
    concept: {
      label: 'I · Premise',
      title: 'Six children who are afraid to <em>fall asleep</em>.',
      lead: 'You are the night caretaker of a quiet dormitory where six girls live, and where every evening ends the same way — with a whisper, a held hand, and a sword waiting just past the threshold of sleep.',
      p1: 'Each room holds a girl. Each girl holds a fear. You speak to them — really speak, with your own voice — and they answer in theirs. They remember what you said the night before. They notice when you forget.',
      p2: 'When one of them finally drifts off, you say <em>the word</em>. The room dims. You step inside the dream. There is a monster waiting. You are not unarmed.',
      facts: [
        ['Title', 'Yume no Ma <span class="jp">夢の間</span>'],
        ['Setting', 'Hisagi Academy <span class="jp">秘崎学園</span>'],
        ['Genre', 'Narrative VR · Kawaii horror'],
        ['Length', '8–12 hours · replayable'],
        ['Languages', 'Japanese · English · Spanish'],
        ['Platforms', 'Steam VR · Desktop'],
        ['Demo', 'Steam Next Fest · Feb 2027'],
      ],
    },
    loop: {
      label: 'II · The Loop',
      title: 'One night, three movements.',
      phases: [
        { num: 'PHASE I',  title: '<em>Evening.</em>', jp: '夕 · yū',   body: 'Walk the corridor. Knock on a door. Sit on the edge of the bed. The microphone is hot — speak, and they will hear you.' },
        { num: 'PHASE II', title: '<em>Night.</em>',   jp: '夜 · yoru', body: 'The breathing slows. Lean close. Whisper the word — <em>dream</em>, <em>夢</em>. The room folds inward. The light changes.' },
        { num: 'PHASE III',title: '<em>The dream.</em>',jp: '夢 · yume', body: 'A blade settles in your hand without weight. Something is breathing in the dark. Whatever they fear, you fight. Win, and tomorrow they will be lighter.' },
      ],
    },
    trailer: {
      label: 'III · The Reveal',
      title: 'A first <em>look</em> — soon.',
      kanji: '夢の間',
      play: 'Trailer · Coming soon',
      meta: 'Gameplay reveal · 2027',
      stamp: 'TR · 0001',
      stamp_r: '夢 / TRAILER',
      audio_sub: 'OST · Excerpt',
      audio_roman: "Rin's Theme",
    },
    cta: {
      eyebrow: 'Wishlist · Steam · Q4 2027',
      title: 'Stay <em>with us</em><br/>until the lamps go out.',
      sub: 'Wishlist on Steam. Be there for the first night.',
      btn: 'Wishlist on Steam',
      btn2: 'Notify me',
    },
    foot: {
      tag: 'A dream before the last one.',
      build: ['Devlog', 'About the developer', ['Contact', 'mailto:tmusharapov@bk.ru']],
      follow: ['@YumeNoMaVR · YouTube', '@YumeNoMaVR · Instagram'],
      copyright: '© 2026 Yume no Ma · A solo project · Releasing Q4 2027',
      whisper: '夢主は見ている',
      press: 'Press kit',
    },
    char: {
      hero_title: 'Six rooms. Six <em>dreamers</em>.',
      hero_lede: 'Each carries a name, a voice, and a monster of their own. Hover to hear how they speak.',
      age_label: 'Age',
      list: [
        { num: '01', name: '酒井 雛子', roman: 'Sakai Hinako · The Quiet One', age: '15', trait: 'Speaks softly · keeps the rabbit close', quote: '"If I am quiet enough, maybe none of them will look at me. I have practiced this for years."', img: 'assets/hinako.jpg', pos: 'center 18%' },
        { num: '02', name: '月之輪 桃絵', roman: 'Tsukinowa Momoe · The Bright One', age: '14', trait: 'Sings the loudest · needs an audience', quote: '"If I keep smiling wide enough, no one looks long enough to see the part that\'s shaking."', img: 'assets/momoe.jpg', pos: 'center 18%' },
        { num: '03', name: '楓 一美', roman: 'Kaede Kazumi · The Composed One', age: '17', trait: 'Plays the cello · keeps her face still', quote: '"There is a way I am supposed to sound. I have not heard it yet."', img: 'assets/hitomi.jpg', pos: 'center 22%' },
        { num: '04', name: '佐藤 凛', roman: 'Satō Rin · The Restless One', age: '15', trait: 'Trains until exhaustion · refuses to slow', quote: '"Sleep is for tomorrow. I am not tired. I am not."', img: 'assets/rin.jpg', pos: 'center 26%' },
        { num: '05', name: '椿 柚子', roman: 'Tsubaki Yuzu · The Watching One', age: '17', trait: 'Sketchbook always open · paints what should not be seen', quote: '"I draw it so that someone, somewhere, finally has to look at it too."', img: 'assets/yuzu.jpg', pos: 'center 22%' },
        { num: '06', name: '白鷺 蒼', roman: 'Shirasagi Aoi · The Knowing One', age: '18', trait: 'Eldest · reads the dormitory like a map', quote: '"Do not ask me yet. You are not ready for the answer. Neither am I."', img: 'assets/aoi.jpg', pos: 'center 28%' },
      ],
    },
  },
  jp: {
    nav: { home: 'ホーム', characters: '登場人物' },
    hero: {
      eyebrow: 'VR & デスクトップ · Steam · 2027年第4四半期',
      tagline: 'A dream before the last one.',
      meta_left: '第零章 · 寮の管理人',
      meta_right: 'スクロールして入る',
    },
    concept: {
      label: '壱 · 物語',
      title: '眠るのが <em>こわい</em> 六人の子ども。',
      lead: 'あなたはこの静かな寮の夜の管理人。六人の子どもがここに住んでいて、毎晩はいつも同じ終わり方をする — ささやきと、握った手と、眠りの境界の向こうで待つ一振りの剣で。',
      p1: '部屋ごとに少女がひとり。少女ごとに恐れがひとつ。あなたは彼らと話す — 自分の声で、本当に。彼らもまた、自分の声で答える。昨夜の言葉を覚えている。あなたが忘れたときには、気づく。',
      p2: '誰かがようやく眠りに落ちたとき、あなたは <em>その言葉</em> を口にする。部屋が暗くなる。あなたは夢の中に踏み込む。怪物がそこにいる。けれどあなたは、丸腰ではない。',
      facts: [
        ['題名', '夢の間 <span class="jp">Yume no Ma</span>'],
        ['舞台', '秘崎学園 <span class="jp">Hisagi Academy</span>'],
        ['ジャンル', 'ナラティブVR · 可愛いホラー'],
        ['長さ', '本編8〜12時間 · 周回可能'],
        ['対応言語', '日本語 · 英語 · スペイン語'],
        ['プラットフォーム', 'Steam VR · デスクトップ'],
        ['体験版', 'Steam Next Fest · 2027年2月'],
      ],
    },
    loop: {
      label: '弐 · ループ',
      title: '一夜、三つの章。',
      phases: [
        { num: '第一段', title: '<em>夕</em>', jp: 'yū · evening', body: '廊下を歩く。扉を叩く。ベッドの端に腰を下ろす。マイクは生きている — 声を出せば、彼らには届く。' },
        { num: '第二段', title: '<em>夜</em>', jp: 'yoru · night',   body: '寝息が穏やかになる。顔を寄せる。その言葉をささやく — <em>夢</em>。部屋が内側に折りたたまれる。光が変わる。' },
        { num: '第三段', title: '<em>夢</em>', jp: 'yume · dream',   body: '重さのない剣が手に収まる。暗がりで何かが息をしている。彼らが恐れるもの、あなたが斬る。勝てば、明日の彼らは少しだけ軽くなる。' },
      ],
    },
    trailer: {
      label: '参 · 予告',
      title: '最初の<em>映像</em>、まもなく。',
      kanji: '夢の間',
      play: 'トレーラー · 近日公開',
      meta: 'ゲームプレイ初公開 · 2027年',
      stamp: 'TR · 0001',
      stamp_r: '夢 / 予告編',
      audio_sub: 'OST · 抜粋',
      audio_roman: '凛のテーマ',
    },
    cta: {
      eyebrow: 'ウィッシュリスト · Steam · 2027 Q4',
      title: '<em>灯</em>が消えるまで、<br/>そばにいて。',
      sub: 'Steamのウィッシュリストへ。最初の夜に、立ち会って。',
      btn: 'Steamでウィッシュリスト',
      btn2: '通知を受け取る',
    },
    foot: {
      tag: 'A dream before the last one.',
      build: ['開発日誌', '開発者について', ['お問い合わせ', 'mailto:tmusharapov@bk.ru']],
      follow: ['@YumeNoMaVR · YouTube', '@YumeNoMaVR · Instagram'],
      copyright: '© 2026 夢の間 · 個人開発 · 2027年Q4発売予定',
      whisper: '夢主は見ている',
      press: 'プレスキット',
    },
    char: {
      hero_title: '六つの部屋、六人の <em>夢見る者</em>。',
      hero_lede: '彼らはそれぞれ、名前と、声と、自分だけの怪物を抱えている。ホバーすれば、彼らの声が聞こえてくる。',
      age_label: '歳',
      list: [
        { num: '一', name: '酒井 雛子', roman: 'Sakai Hinako · 静かな子', age: '15', trait: '小さな声で話す · うさぎを離さない', quote: '「静かにしていれば、誰も私を見ないかもしれない。何年もそう練習してきた。」', img: 'assets/hinako.jpg', pos: 'center 18%' },
        { num: '二', name: '月之輪 桃絵', roman: 'Tsukinowa Momoe · まぶしい子', age: '14', trait: '誰よりも大きく歌う · 観客を欲しがる', quote: '「目一杯笑っていれば、誰も震えているところまでは見ない。」', img: 'assets/momoe.jpg', pos: 'center 18%' },
        { num: '三', name: '楓 一美', roman: 'Kaede Kazumi · 静謐な子', age: '17', trait: 'チェロを弾く · 顔を動かさない', quote: '「私が出すべき音がある。まだ聴いたことがない。」', img: 'assets/hitomi.jpg', pos: 'center 22%' },
        { num: '四', name: '佐藤 凛', roman: 'Satō Rin · 落ち着かない子', age: '15', trait: '倒れるまで走る · 止まることを拒む', quote: '「眠るのは明日でいい。疲れていない。本当だ。」', img: 'assets/rin.jpg', pos: 'center 26%' },
        { num: '五', name: '椿 柚子', roman: 'Tsubaki Yuzu · 観る子', age: '17', trait: 'スケッチブックは常に開いている · 見てはいけないものを描く', quote: '「描けば、誰かがいつか、それを見ないわけにはいかなくなる。」', img: 'assets/yuzu.jpg', pos: 'center 22%' },
        { num: '六', name: '白鷺 蒼', roman: 'Shirasagi Aoi · 知っている子', age: '18', trait: '最年長 · 寮を地図のように読む', quote: '「まだ訊かないで。あなたは答えに耐えられない。私もまだ。」', img: 'assets/aoi.jpg', pos: 'center 28%' },
      ],
    },
  },
  es: {
    nav: { home: 'Inicio', characters: 'Personajes' },
    hero: {
      eyebrow: 'Una experiencia VR & Escritorio · Steam · T4 2027',
      tagline: 'Un sueño antes del último.',
      meta_left: 'CAP. 00 · El cuidador',
      meta_right: 'Desliza para entrar',
    },
    concept: {
      label: 'I · Premisa',
      title: 'Seis niñas que tienen miedo de <em>quedarse dormidas</em>.',
      lead: 'Eres el cuidador nocturno de un internado silencioso donde viven seis niñas, y donde cada noche termina igual — con un susurro, una mano sostenida, y una espada esperando justo al otro lado del umbral del sueño.',
      p1: 'Cada habitación guarda a una niña. Cada niña guarda un miedo. Hablas con ellas — de verdad, con tu propia voz — y ellas responden con la suya. Recuerdan lo que dijiste anoche. Notan cuando lo olvidas.',
      p2: 'Cuando una de ellas finalmente cae dormida, tú dices <em>la palabra</em>. La habitación se oscurece. Entras en el sueño. Hay un monstruo esperando. No estás desarmado.',
      facts: [
        ['Título', 'Yume no Ma <span class="jp">夢の間</span>'],
        ['Escenario', 'Academia Hisagi <span class="jp">秘崎学園</span>'],
        ['Género', 'VR narrativo · Kawaii horror'],
        ['Duración', '8–12 horas · rejugable'],
        ['Idiomas', 'Japonés · Inglés · Español'],
        ['Plataformas', 'Steam VR · Escritorio'],
        ['Demo', 'Steam Next Fest · Feb 2027'],
      ],
    },
    loop: {
      label: 'II · El ciclo',
      title: 'Una noche, tres movimientos.',
      phases: [
        { num: 'FASE I',   title: '<em>Atardecer.</em>', jp: '夕 · yū',   body: 'Recorre el pasillo. Toca una puerta. Siéntate al borde de la cama. El micrófono está vivo — habla, y ella te oirá.' },
        { num: 'FASE II',  title: '<em>Noche.</em>',     jp: '夜 · yoru', body: 'La respiración se calma. Acércate. Susurra la palabra — <em>sueño</em>, <em>夢</em>. La habitación se pliega hacia adentro. La luz cambia.' },
        { num: 'FASE III', title: '<em>El sueño.</em>',  jp: '夢 · yume', body: 'Una hoja se acomoda en tu mano sin peso. Algo respira en la oscuridad. Lo que ella tema, tú lo combates. Vence, y mañana ella estará más ligera.' },
      ],
    },
    trailer: {
      label: 'III · El anuncio',
      title: 'Un primer <em>vistazo</em> — pronto.',
      kanji: '夢の間',
      play: 'Tráiler · Próximamente',
      meta: 'Revelación de gameplay · 2027',
      stamp: 'TR · 0001',
      stamp_r: '夢 / TRÁILER',
      audio_sub: 'BSO · Extracto',
      audio_roman: 'Tema de Rin',
    },
    cta: {
      eyebrow: 'Lista de deseos · Steam · T4 2027',
      title: 'Quédate <em>con nosotras</em><br/>hasta que se apaguen las lámparas.',
      sub: 'Añádelo a tu lista de deseos en Steam. Estate ahí la primera noche.',
      btn: 'Añadir a deseados',
      btn2: 'Avísame',
    },
    foot: {
      tag: 'Un sueño antes del último.',
      build: ['Diario', 'Sobre el desarrollador', ['Contacto', 'mailto:tmusharapov@bk.ru']],
      follow: ['@YumeNoMaVR · YouTube', '@YumeNoMaVR · Instagram'],
      copyright: '© 2026 Yume no Ma · Proyecto en solitario · Lanzamiento T4 2027',
      whisper: '夢主は見ている',
      press: 'Kit de prensa',
    },
    char: {
      hero_title: 'Seis habitaciones. Seis <em>soñadoras</em>.',
      hero_lede: 'Cada una lleva un nombre, una voz y un monstruo propio. Pasa el cursor para oír cómo hablan.',
      age_label: 'Edad',
      list: [
        { num: '01', name: '酒井 雛子', roman: 'Sakai Hinako · La silenciosa', age: '15', trait: 'Habla en voz baja · siempre con su conejo', quote: '«Si me quedo lo bastante quieta, quizá ninguno me mire. Llevo años practicándolo.»', img: 'assets/hinako.jpg', pos: 'center 18%' },
        { num: '02', name: '月之輪 桃絵', roman: 'Tsukinowa Momoe · La luminosa', age: '14', trait: 'Canta más fuerte que nadie · necesita público', quote: '«Si sonrío lo suficiente, nadie mira el tiempo necesario para ver lo que tiembla.»', img: 'assets/momoe.jpg', pos: 'center 18%' },
        { num: '03', name: '楓 一美', roman: 'Kaede Kazumi · La serena', age: '17', trait: 'Toca el cello · no mueve el rostro', quote: '«Hay un sonido que se supone que debo hacer. Aún no lo he oído.»', img: 'assets/hitomi.jpg', pos: 'center 22%' },
        { num: '04', name: '佐藤 凛', roman: 'Satō Rin · La inquieta', age: '15', trait: 'Entrena hasta caerse · se niega a parar', quote: '«Dormir es para mañana. No estoy cansada. No lo estoy.»', img: 'assets/rin.jpg', pos: 'center 26%' },
        { num: '05', name: '椿 柚子', roman: 'Tsubaki Yuzu · La que observa', age: '17', trait: 'Cuaderno siempre abierto · pinta lo que no debería verse', quote: '«Lo dibujo para que alguien, en alguna parte, no pueda evitar mirarlo también.»', img: 'assets/yuzu.jpg', pos: 'center 22%' },
        { num: '06', name: '白鷺 蒼', roman: 'Shirasagi Aoi · La que sabe', age: '18', trait: 'La mayor · lee el internado como un mapa', quote: '«No me preguntes todavía. No estás listo para la respuesta. Yo tampoco.»', img: 'assets/aoi.jpg', pos: 'center 28%' },
      ],
    },
  },
};

const PRESS_COPY = {
  en: {
    hero_eyebrow: 'Press kit · 報道資料',
    hero_title: 'Press <em>kit</em>.',
    hero_sub: 'Everything you need to write about Yume no Ma — fact sheet, palette, quotes, and a contact that answers.',
    side: { contact: 'Contact', email: 'tmusharapov@bk.ru', dev: 'Tim Musharapov · Solo developer · Releasing Q4 2027', socials: 'Socials', release: 'Release', release_v: 'Q4 2027 · Steam · Demo at Steam Next Fest, Feb 2027' },
    blocks: [
      { num: '01', title: 'About <em>the game</em>', body: '<p>Yume no Ma <span class="kanji">夢の間</span> is a narrative VR experience built on real-time AI conversation. The player is the night caretaker of a quiet dormitory at Hisagi Academy, where six children live. Each evening, the player tucks them into bed using their own voice — and when sleep comes, steps into the child\'s dream, sword in hand, to fight the monster of that one\'s personal fear.</p><p>Behind a soft kawaii surface, the game gradually unfolds a stranger story: about what this dormitory really is, what is watching from beyond the dreams, and why these six children are gathered here.</p>' },
      { num: '02', title: 'Fact <em>sheet</em>' },
      { num: '03', title: 'Story <em>quotes</em>' },
      { num: '04', title: 'Brand <em>palette</em>' },
      { num: '05', title: 'Downloads' },
    ],
    facts: [
      ['Title', 'Yume no Ma <span class="jp">夢の間</span>'],
      ['Tagline', 'A dream before the last one.'],
      ['Setting', 'Hisagi Academy <span class="jp">秘崎学園</span>'],
      ['Developer', 'Tim Musharapov · solo'],
      ['Engine', 'Unity 6'],
      ['Platforms', 'Steam VR · PC Desktop'],
      ['Languages', 'Japanese · English · Spanish'],
      ['Genre', 'Narrative VR · Kawaii horror · AI conversation'],
      ['Length', '8–12 hours main story'],
      ['Price', '$19.99 – 24.99 USD'],
      ['Release', 'Q4 2027 · planned'],
      ['Demo', 'Steam Next Fest · February 2027 · free'],
    ],
    quotes: [
      ['"This VR game actually listens to what I say."', 'Marketing direction · short-form'],
      ['"She remembers what I told her yesterday."', 'Marketing direction · player POV'],
      ['"Six children. Six dreams. Six monsters."', 'Tagline alt'],
      ['"A whisper can calm her. A sword can save her."', 'Tagline alt'],
    ],
    swatches: [
      ['Watercolor paper', '#F1E8D4'],
      ['Sumi ink', '#2B221A'],
      ['Terracotta', '#B5654E'],
      ['Aged gold', '#B8852A'],
    ],
    downloads: [
      ['夢', 'Logo pack', 'SVG · PNG · 4 MB'],
      ['図', 'Screenshot bundle', 'PNG · 24 MB'],
      ['書', 'Press release', 'PDF · 30.6 MB', 'assets/yume_no_ma_press_release.pdf'],
    ],
  },
  jp: {
    hero_eyebrow: 'プレスキット · 報道資料',
    hero_title: 'プレス <em>キット</em>',
    hero_sub: '夢の間について書くために必要なすべて — ファクトシート、パレット、引用句、そして返信の届く連絡先。',
    side: { contact: '連絡先', email: 'tmusharapov@bk.ru', dev: 'Tim Musharapov · 個人開発者 · 2027年Q4発売', socials: 'SNS', release: 'リリース', release_v: '2027 Q4 · Steam · 体験版は2027年2月のSteam Next Festにて' },
    blocks: [
      { num: '一', title: '<em>ゲーム</em>について', body: '<p>夢の間 <span class="kanji">Yume no Ma</span> は、リアルタイムAI会話を中核に据えたナラティブVR体験。プレイヤーは秘崎学園の静かな寮の夜の管理人として、そこに住む六人の子どもを毎晩寝かしつける — 自分の声で。彼らが眠りに落ちたら、剣を手に夢の中へ踏み込み、それぞれの恐怖の化身と戦う。</p><p>柔らかな可愛さの表面の奥には、より静かで奇妙な物語がある — この寮が本当は何なのか、夢の向こうから何が見つめているのか、なぜ六人の子どもがここに集められたのか。</p>' },
      { num: '二', title: 'ファクト <em>シート</em>' },
      { num: '三', title: '物語の <em>断片</em>' },
      { num: '四', title: 'ブランド <em>パレット</em>' },
      { num: '五', title: 'ダウンロード' },
    ],
    facts: [
      ['題名', '夢の間 <span class="jp">Yume no Ma</span>'],
      ['キャッチ', 'A dream before the last one.'],
      ['舞台', '秘崎学園 <span class="jp">Hisagi Academy</span>'],
      ['開発者', 'Tim Musharapov · 個人開発'],
      ['エンジン', 'Unity 6'],
      ['プラットフォーム', 'Steam VR · PC デスクトップ'],
      ['対応言語', '日本語 · 英語 · スペイン語'],
      ['ジャンル', 'ナラティブVR · 可愛いホラー · AI会話'],
      ['長さ', '本編 8〜12 時間'],
      ['価格', '$19.99 – 24.99 USD'],
      ['リリース', '2027 Q4 · 予定'],
      ['体験版', 'Steam Next Fest · 2027年2月 · 無料'],
    ],
    quotes: [
      ['「このVRゲーム、本当に話を聞いてくれる。」', 'マーケティング · ショート'],
      ['「昨日言ったこと、覚えてくれてた。」', 'マーケティング · プレイヤー視点'],
      ['「六人の子ども、六つの夢、六匹の怪物。」', 'タグライン候補'],
      ['「ささやきが彼女を落ち着かせる。剣が彼女を救う。」', 'タグライン候補'],
    ],
    swatches: [
      ['和紙の色', '#F1E8D4'],
      ['墨', '#2B221A'],
      ['赤土', '#B5654E'],
      ['古びた金', '#B8852A'],
    ],
    downloads: [
      ['夢', 'ロゴパック', 'SVG · PNG · 4 MB'],
      ['図', 'スクリーンショット集', 'PNG · 24 MB'],
      ['書', 'プレスリリース', 'PDF · 30.6 MB', 'assets/yume_no_ma_press_release.pdf'],
    ],
  },
  es: {
    hero_eyebrow: 'Kit de prensa · 報道資料',
    hero_title: 'Kit de <em>prensa</em>.',
    hero_sub: 'Todo lo que necesitas para escribir sobre Yume no Ma — ficha técnica, paleta, citas, y un contacto que responde.',
    side: { contact: 'Contacto', email: 'tmusharapov@bk.ru', dev: 'Tim Musharapov · Desarrollador en solitario · Lanzamiento T4 2027', socials: 'Redes', release: 'Lanzamiento', release_v: 'T4 2027 · Steam · Demo en Steam Next Fest, feb 2027' },
    blocks: [
      { num: '01', title: 'Sobre <em>el juego</em>', body: '<p>Yume no Ma <span class="kanji">夢の間</span> es una experiencia VR narrativa construida sobre conversación con IA en tiempo real. El jugador es el cuidador nocturno de un internado silencioso en la Academia Hisagi, donde viven seis niñas. Cada noche, las acuesta usando su propia voz — y cuando llega el sueño, entra en el sueño de cada una, espada en mano, para combatir el monstruo de su miedo personal.</p><p>Detrás de una superficie kawaii suave, el juego despliega lentamente una historia más extraña: sobre lo que este internado realmente es, lo que mira desde más allá de los sueños, y por qué estas seis niñas están reunidas aquí.</p>' },
      { num: '02', title: 'Ficha <em>técnica</em>' },
      { num: '03', title: 'Citas <em>narrativas</em>' },
      { num: '04', title: 'Paleta <em>de marca</em>' },
      { num: '05', title: 'Descargas' },
    ],
    facts: [
      ['Título', 'Yume no Ma <span class="jp">夢の間</span>'],
      ['Eslogan', 'Un sueño antes del último.'],
      ['Escenario', 'Academia Hisagi <span class="jp">秘崎学園</span>'],
      ['Desarrollador', 'Tim Musharapov · en solitario'],
      ['Motor', 'Unity 6'],
      ['Plataformas', 'Steam VR · PC Escritorio'],
      ['Idiomas', 'Japonés · Inglés · Español'],
      ['Género', 'VR narrativo · Kawaii horror · Conversación con IA'],
      ['Duración', '8–12 horas (historia principal)'],
      ['Precio', '$19.99 – 24.99 USD'],
      ['Lanzamiento', 'T4 2027 · planificado'],
      ['Demo', 'Steam Next Fest · febrero 2027 · gratuita'],
    ],
    quotes: [
      ['«Este VR de verdad escucha lo que digo.»', 'Dirección de marketing · corto'],
      ['«Recuerda lo que le dije ayer.»', 'Dirección de marketing · POV jugador'],
      ['«Seis niñas. Seis sueños. Seis monstruos.»', 'Eslogan alt'],
      ['«Un susurro la calma. Una espada la salva.»', 'Eslogan alt'],
    ],
    swatches: [
      ['Papel acuarela', '#F1E8D4'],
      ['Tinta sumi', '#2B221A'],
      ['Terracota', '#B5654E'],
      ['Oro envejecido', '#B8852A'],
    ],
    downloads: [
      ['夢', 'Pack de logos', 'SVG · PNG · 4 MB'],
      ['図', 'Capturas', 'PNG · 24 MB'],
      ['書', 'Nota de prensa', 'PDF · 30.6 MB', 'assets/yume_no_ma_press_release.pdf'],
    ],
  },
};

window.COPY = COPY;
window.PRESS_COPY = PRESS_COPY;
